version: 0.2

phases:
  install:
    runtime-versions:
      docker: 23
    commands:
      - echo Installing Docker Buildx...
      - mkdir -p /usr/libexec/docker/cli-plugins
      - curl -sSL https://github.com/docker/buildx/releases/download/v0.10.4/buildx-v0.10.4.linux-amd64 -o /usr/libexec/docker/cli-plugins/docker-buildx
      - chmod +x /usr/libexec/docker/cli-plugins/docker-buildx
      - docker buildx version
      - docker buildx create --name mybuilder --driver docker-container --use
      - docker buildx inspect mybuilder --bootstrap
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 654455900232.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image for amd64...
      - docker buildx build --platform linux/amd64 -t nodepipeline-devops . --load
      - docker tag nodepipeline-devops:latest 654455900232.dkr.ecr.us-east-1.amazonaws.com/nodepipeline-devops:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 654455900232.dkr.ecr.us-east-1.amazonaws.com/nodepipeline-devops:latest
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"nodepipeline-devops","imageUri":"%s"}]' 654455900232.dkr.ecr.us-east-1.amazonaws.com/nodepipeline-devops:latest > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
